# Generated by Django 4.0.3 on 2022-04-12 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('cardTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('director', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('synopsis', models.CharField(max_length=500)),
                ('rating', models.CharField(max_length=5)),
                ('playing_now', models.BooleanField(default=False)),
                ('trailer_picture', models.URLField(blank=True, max_length=300)),
                ('trailer_video', models.URLField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MovieCategory',
            fields=[
                ('category', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.IntegerField(default=20000000000)),
                ('enrollForPromotions', models.BooleanField(default=False)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('time', models.DateTimeField(default='12/12/12 12:12', primary_key=True, serialize=False)),
                ('movieID', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='cat',
            field=models.ForeignKey(default='Action', on_delete=django.db.models.deletion.CASCADE, to='home.moviecategory'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountID', models.AutoField(primary_key=True, serialize=False)),
                ('cardNo', models.CharField(max_length=250)),
                ('expirationDate', models.DateField()),
                ('billingAdd', models.CharField(max_length=45)),
                ('user_userID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
