# Generated by Django 4.0.3 on 2022-04-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer_picture',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
