# Generated by Django 4.0.3 on 2022-05-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticketID',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seatNum',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
