# Generated by Django 4.0.3 on 2022-04-16 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user_userID',
            new_name='user',
        ),
    ]
