# Generated by Django 4.0.3 on 2022-04-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='time',
            field=models.CharField(default='12/12/12 12:12', max_length=50, primary_key=True, serialize=False),
        ),
    ]
