# Generated by Django 4.0.3 on 2022-04-17 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='exp',
            field=models.DateField(default=datetime.date(2022, 4, 17)),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
