# Generated by Django 4.0.3 on 2022-03-22 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardtype',
            name='account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userStatus',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userType',
        ),
        migrations.AddField(
            model_name='account',
            name='user_userID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.user'),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='account_accountID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.account'),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='user_userID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.user'),
        ),
        migrations.AddField(
            model_name='usertype',
            name='user_userID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.user'),
        ),
    ]
