# Generated by Django 4.0.3 on 2022-05-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_ticket_ticketid_alter_ticket_seatnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticketID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seatNum',
            field=models.IntegerField(default=1),
        ),
    ]
