# Generated by Django 4.0.3 on 2022-03-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_user_id_user_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=20000000000),
        ),
    ]
