# Generated by Django 4.0.3 on 2022-04-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cardencr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='billingAdd',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='account',
            name='cardNo',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='account',
            name='exp',
            field=models.DateField(blank=True),
        ),
    ]
