# Generated by Django 4.0.3 on 2022-05-03 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_order_numtickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='numTickets',
        ),
    ]
