# Generated by Django 4.0.3 on 2022-03-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_cardtype_account_remove_user_userstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountID',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
