# Generated by Django 4.0.3 on 2022-04-16 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_user_userid_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='billingAdd',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='account',
            name='cardNo',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='account',
            name='exp',
            field=models.DateField(default=datetime.datetime(2022, 4, 16, 18, 29, 35, 534418)),
        ),
    ]
