# Generated by Django 4.0.3 on 2022-04-16 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_account_billingadd_alter_account_cardno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='exp',
            field=models.DateField(default=datetime.datetime(2022, 4, 16, 19, 13, 43, 966325)),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=45),
        ),
    ]
