# Generated by Django 4.0.3 on 2022-03-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_account_accountid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtype',
            name='cardTypeID',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='userStatusID',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='userTypeID',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
