# Generated by Django 4.0.3 on 2022-05-03 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_order_numtickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='numTickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='showtimeID',
            field=models.ForeignKey(default='12/12/12 12:12', on_delete=django.db.models.deletion.CASCADE, to='home.showtime'),
        ),
    ]
