# Generated by Django 4.0.3 on 2022-04-24 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_order_seat_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='movieID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.movie'),
        ),
        migrations.AddField(
            model_name='seat',
            name='showtimeID',
            field=models.ForeignKey(default='12/12/12 12:12', on_delete=django.db.models.deletion.CASCADE, to='home.showtime'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='movieID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.movie'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='ticket',
            name='showtimeID',
            field=models.ForeignKey(default='12/12/12 12:12', on_delete=django.db.models.deletion.CASCADE, to='home.showtime'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
