# Generated by Django 4.0.3 on 2022-03-23 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_cardtype_cardtypeid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatus',
            name='user_userID',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='user_userID',
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.usertype'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.userstatus'),
        ),
    ]
