# Generated by Django 4.0.3 on 2022-05-03 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_order_numtickets_order_showtimeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accountID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.account'),
        ),
    ]
