# Generated by Django 4.0.3 on 2022-03-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cardNo',
            field=models.CharField(max_length=250),
        ),
    ]
