# Generated by Django 4.0.3 on 2022-04-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_order_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='movieID',
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.IntegerField(default=10),
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
