# Generated by Django 4.0.3 on 2022-03-23 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_userstatus_user_userid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='enrollForPromotions',
        ),
    ]
