# Generated by Django 4.0.3 on 2022-05-03 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_order_accountid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='accountID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.account'),
        ),
        migrations.AlterField(
            model_name='order',
            name='numTickets',
            field=models.FloatField(default=0),
        ),
    ]
