# Generated by Django 4.0.3 on 2022-03-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_user_enrollforpromotions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='userStatusID',
            field=models.IntegerField(default=2, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='userTypeID',
            field=models.IntegerField(default=2, primary_key=True, serialize=False),
        ),
    ]
