# Generated by Django 4.0.3 on 2022-05-05 18:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_order_accountid_alter_order_numtickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='exp',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
        ),
    ]
