# Generated by Django 4.0.3 on 2022-03-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_account_cardno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='enrollForPromotions',
            field=models.BooleanField(default=False),
        ),
    ]
