# Generated by Django 4.0.3 on 2022-05-05 18:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_account_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='exp',
            field=models.DateField(default=datetime.datetime(2022, 5, 5, 18, 40, 57, 640720, tzinfo=utc)),
        ),
    ]
