# Generated by Django 4.0.3 on 2022-03-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_user_enrollforpromotions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('synopsis', models.CharField(max_length=500)),
                ('rating', models.CharField(max_length=5)),
                ('trailer_picture', models.ImageField(upload_to=None)),
                ('trailer_video', models.URLField(max_length=250)),
                ('playing_now', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('showtimeID', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
