# Generated by Django 4.0.3 on 2022-04-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_ticket_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticketID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
