# Generated by Django 4.0.3 on 2022-05-05 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_account_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='exp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
