# Generated by Django 4.0.3 on 2022-04-29 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_ticket_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('ticketID', 'showtimeID')},
        ),
    ]
