# Generated by Django 4.0.3 on 2022-04-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_ticket_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticketID',
            field=models.IntegerField(default=1),
        ),
    ]
