# Generated by Django 4.0.3 on 2022-04-29 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_ticket_id_alter_ticket_ticketid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticketID',
            new_name='seatNum',
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('seatNum', 'showtimeID')},
        ),
    ]
